# Generated by Django 3.2.12 on 2022-02-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_editor',
        ),
    ]
